#pragma once
#include <vector>
#include <string>
#include "imgui.h"

// A structure to hold everything related to our 3D Head
struct HeadModelData {
    bool isLoaded = false;

    // 3D Geometry Data
    std::vector<float> vertices;

    // Graphics API IDs (Generated by OpenGL/DirectX)
    unsigned int fboID = 0;           // Framebuffer Object ID
    unsigned int renderTextureID = 0; // The actual picture we hand to ImGui

    // Interaction State
    float rotationX = 0.0f;
    float rotationY = 0.0f;
};

class HeadObject {
private:
    HeadModelData my3DHead;

    // Hidden rendering function (draws the 3D head to a texture)
    void RenderHeadToFramebuffer(ImVec2 viewportSize);

public:
    HeadObject() = default;
    ~HeadObject() = default;

    // Called ONCE when the app starts
    void InitModel(const std::string& objFilePath, const std::string& mtlSearchPath);

    // Called EVERY FRAME from your UI.cpp inside the TabItem
    void Draw();
};